spring.application.name=local-services-finder
spring.profiles.default=local

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/najdi_usluga?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.google-maps-api-key=${GOOGLE_MAPS_API_KEY:}
